name: "Cybersecurity Dashboard"
version: "dev"
slug: "cybersecurity_dashboard"
description: "Improve your cybersecurity of your smart home"
panel_icon: "mdi:security"
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 8080
hassio_api: true
homeassistant_api: true
options:
  instance_url: "localhost"
schema:
  instance_url: "str"