// This file is auto-generated by @hey-api/openapi-ts

export const CoreInfoDtoSchema = {
    type: 'object',
    required: ['version', 'version_latest', 'update_available', 'arch', 'machine', 'ip_address', 'image'],
    properties: {
        version: {
            type: 'string'
        },
        version_latest: {
            type: 'string'
        },
        update_available: {
            type: 'string'
        },
        arch: {
            type: 'string'
        },
        machine: {
            type: 'string'
        },
        ip_address: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        boot: {
            type: 'boolean'
        },
        port: {
            type: 'integer',
            format: 'int32'
        },
        ssl: {
            type: 'boolean'
        },
        watchdog: {
            type: 'boolean'
        },
        wait_boot: {
            type: 'integer',
            format: 'int32'
        },
        audio_input: {
            type: ['string', 'null']
        },
        audio_output: {
            type: ['string', 'null']
        },
        backups_exclude_database: {
            type: 'boolean'
        }
    }
} as const;

export const ResultDtoCoreInfoDtoSchema = {
    type: 'object',
    required: ['result'],
    properties: {
        result: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/CoreInfoDto'
        }
    }
} as const;