// This file is auto-generated by @hey-api/openapi-ts

export const CheckSchema = {
    type: 'object',
    required: ['name', 'description'],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CheckReportSchema = {
    type: 'object',
    required: ['timestamp', 'results'],
    properties: {
        timestamp: {
            '$ref': '#/components/schemas/Instant'
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CheckResult'
            }
        }
    }
} as const;

export const CheckResultSchema = {
    type: 'object',
    required: ['check', 'risk'],
    properties: {
        check: {
            '$ref': '#/components/schemas/Check'
        },
        risk: {
            '$ref': '#/components/schemas/Risk'
        },
        message: {
            type: ['string', 'null']
        }
    }
} as const;

export const InstantSchema = {
    type: 'string',
    format: 'date-time',
    examples: ['2022-03-10T16:15:50Z']
} as const;

export const RiskSchema = {
    type: 'string',
    enum: ['NONE', 'LOW', 'MODERATE', 'HIGH']
} as const;