// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetHomeassistantCoreInfoError, GetHomeassistantCoreInfoResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Core Info
 */
export const getHomeassistantCoreInfo = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetHomeassistantCoreInfoResponse, GetHomeassistantCoreInfoError, ThrowOnError>({
    ...options,
    url: '/homeassistant/core/info'
}); };