// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiHomeAssistantCoreInfoError, GetApiHomeAssistantCoreInfoResponse, GetApiHomeAssistantDumpEnvError, GetApiHomeAssistantDumpEnvResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Core Info
 */
export const getApiHomeAssistantCoreInfo = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiHomeAssistantCoreInfoResponse, GetApiHomeAssistantCoreInfoError, ThrowOnError>({
    ...options,
    url: '/api/home-assistant/core/info'
}); };

/**
 * Post Log Token
 */
export const getApiHomeAssistantDumpEnv = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiHomeAssistantDumpEnvResponse, GetApiHomeAssistantDumpEnvError, ThrowOnError>({
    ...options,
    url: '/api/home-assistant/dump-env'
}); };