// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetHaCoreInfoError, GetHaCoreInfoResponse, GetHaDumpEnvError, GetHaDumpEnvResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Core Info
 */
export const getHaCoreInfo = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetHaCoreInfoResponse, GetHaCoreInfoError, ThrowOnError>({
    ...options,
    url: '/ha/core/info'
}); };

/**
 * Post Log Token
 */
export const getHaDumpEnv = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetHaDumpEnvResponse, GetHaDumpEnvError, ThrowOnError>({
    ...options,
    url: '/ha/dump-env'
}); };