// This file is auto-generated by @hey-api/openapi-ts

export type CoreInfoDto = {
    version: string;
    version_latest: string;
    update_available: string;
    arch: string;
    machine: string;
    ip_address: string;
    image: string;
    boot?: boolean;
    port?: number;
    ssl?: boolean;
    watchdog?: boolean;
    wait_boot?: number;
    audio_input?: (string) | null;
    audio_output?: (string) | null;
    backups_exclude_database?: boolean;
};

export type ResultDtoCoreInfoDto = {
    result: string;
    data?: CoreInfoDto;
};

export type GetHaCoreInfoResponse = (ResultDtoCoreInfoDto);

export type GetHaCoreInfoError = unknown;

export type GetHaDumpEnvResponse = (unknown);

export type GetHaDumpEnvError = unknown;