// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { useMutation, UseMutationOptions, useQuery, UseQueryOptions } from "@tanstack/react-query";
import { getApiReport, postApiChecksByIdDisable, postApiChecksByIdEnable, postApiReportGenerate } from "../requests/services.gen";
import { GetApiReportError, PostApiChecksByIdDisableData, PostApiChecksByIdDisableError, PostApiChecksByIdEnableData, PostApiChecksByIdEnableError, PostApiReportGenerateError } from "../requests/types.gen";
import * as Common from "./common";
export const useGetApiReport = <TData = Common.GetApiReportDefaultResponse, TError = GetApiReportError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseGetApiReportKeyFn(clientOptions, queryKey), queryFn: () => getApiReport({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const usePostApiChecksByIdDisable = <TData = Common.PostApiChecksByIdDisableMutationResult, TError = PostApiChecksByIdDisableError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<PostApiChecksByIdDisableData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<PostApiChecksByIdDisableData, true>, TContext>({ mutationKey: Common.UsePostApiChecksByIdDisableKeyFn(mutationKey), mutationFn: clientOptions => postApiChecksByIdDisable(clientOptions) as unknown as Promise<TData>, ...options });
export const usePostApiChecksByIdEnable = <TData = Common.PostApiChecksByIdEnableMutationResult, TError = PostApiChecksByIdEnableError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<PostApiChecksByIdEnableData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<PostApiChecksByIdEnableData, true>, TContext>({ mutationKey: Common.UsePostApiChecksByIdEnableKeyFn(mutationKey), mutationFn: clientOptions => postApiChecksByIdEnable(clientOptions) as unknown as Promise<TData>, ...options });
export const usePostApiReportGenerate = <TData = Common.PostApiReportGenerateMutationResult, TError = PostApiReportGenerateError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<unknown, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<unknown, true>, TContext>({ mutationKey: Common.UsePostApiReportGenerateKeyFn(mutationKey), mutationFn: clientOptions => postApiReportGenerate(clientOptions) as unknown as Promise<TData>, ...options });
