// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostApiChecksByIdDisableData, PostApiChecksByIdDisableError, PostApiChecksByIdDisableResponse, PostApiChecksByIdEnableData, PostApiChecksByIdEnableError, PostApiChecksByIdEnableResponse, GetApiReportError, GetApiReportResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Post Checks Disable
 */
export const postApiChecksByIdDisable = <ThrowOnError extends boolean = false>(options: Options<PostApiChecksByIdDisableData, ThrowOnError>) => { return (options?.client ?? client).post<PostApiChecksByIdDisableResponse, PostApiChecksByIdDisableError, ThrowOnError>({
    ...options,
    url: '/api/checks/{id}/disable'
}); };

/**
 * Post Checks Enable
 */
export const postApiChecksByIdEnable = <ThrowOnError extends boolean = false>(options: Options<PostApiChecksByIdEnableData, ThrowOnError>) => { return (options?.client ?? client).post<PostApiChecksByIdEnableResponse, PostApiChecksByIdEnableError, ThrowOnError>({
    ...options,
    url: '/api/checks/{id}/enable'
}); };

/**
 * Get Report
 */
export const getApiReport = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiReportResponse, GetApiReportError, ThrowOnError>({
    ...options,
    url: '/api/report'
}); };