// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostApiCheckByIdDisableData, PostApiCheckByIdDisableError, PostApiCheckByIdDisableResponse, PostApiCheckByIdEnableData, PostApiCheckByIdEnableError, PostApiCheckByIdEnableResponse, GetApiReportError, GetApiReportResponse, PostApiReportGenerateError, PostApiReportGenerateResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Post Checks Disable
 */
export const postApiCheckByIdDisable = <ThrowOnError extends boolean = false>(options: Options<PostApiCheckByIdDisableData, ThrowOnError>) => { return (options?.client ?? client).post<PostApiCheckByIdDisableResponse, PostApiCheckByIdDisableError, ThrowOnError>({
    ...options,
    url: '/api/check/{id}/disable'
}); };

/**
 * Post Checks Enable
 */
export const postApiCheckByIdEnable = <ThrowOnError extends boolean = false>(options: Options<PostApiCheckByIdEnableData, ThrowOnError>) => { return (options?.client ?? client).post<PostApiCheckByIdEnableResponse, PostApiCheckByIdEnableError, ThrowOnError>({
    ...options,
    url: '/api/check/{id}/enable'
}); };

/**
 * Get Report
 */
export const getApiReport = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiReportResponse, GetApiReportError, ThrowOnError>({
    ...options,
    url: '/api/report'
}); };

/**
 * Post Report Generate
 */
export const postApiReportGenerate = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<PostApiReportGenerateResponse, PostApiReportGenerateError, ThrowOnError>({
    ...options,
    url: '/api/report/generate'
}); };