// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiDevicesError, GetApiDevicesResponse, GetApiLogsError, GetApiLogsResponse, GetApiLogsUnifiedError, GetApiLogsUnifiedResponse, GetApiOverviewError, GetApiOverviewResponse, PostApiOverviewCheckByIdDisableData, PostApiOverviewCheckByIdDisableError, PostApiOverviewCheckByIdDisableResponse, PostApiOverviewCheckByIdEnableData, PostApiOverviewCheckByIdEnableError, PostApiOverviewCheckByIdEnableResponse, PostApiOverviewGenerateError, PostApiOverviewGenerateResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get
 */
export const getApiDevices = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiDevicesResponse, GetApiDevicesError, ThrowOnError>({
    ...options,
    url: '/api/devices'
}); };

/**
 * Get
 */
export const getApiLogs = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiLogsResponse, GetApiLogsError, ThrowOnError>({
    ...options,
    url: '/api/logs'
}); };

/**
 * Get Unified
 */
export const getApiLogsUnified = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiLogsUnifiedResponse, GetApiLogsUnifiedError, ThrowOnError>({
    ...options,
    url: '/api/logs/unified'
}); };

/**
 * Get
 */
export const getApiOverview = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetApiOverviewResponse, GetApiOverviewError, ThrowOnError>({
    ...options,
    url: '/api/overview'
}); };

/**
 * Post Checks Disable
 */
export const postApiOverviewCheckByIdDisable = <ThrowOnError extends boolean = false>(options: Options<PostApiOverviewCheckByIdDisableData, ThrowOnError>) => { return (options?.client ?? client).post<PostApiOverviewCheckByIdDisableResponse, PostApiOverviewCheckByIdDisableError, ThrowOnError>({
    ...options,
    url: '/api/overview/check/{id}/disable'
}); };

/**
 * Post Checks Enable
 */
export const postApiOverviewCheckByIdEnable = <ThrowOnError extends boolean = false>(options: Options<PostApiOverviewCheckByIdEnableData, ThrowOnError>) => { return (options?.client ?? client).post<PostApiOverviewCheckByIdEnableResponse, PostApiOverviewCheckByIdEnableError, ThrowOnError>({
    ...options,
    url: '/api/overview/check/{id}/enable'
}); };

/**
 * Post Generate
 */
export const postApiOverviewGenerate = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<PostApiOverviewGenerateResponse, PostApiOverviewGenerateError, ThrowOnError>({
    ...options,
    url: '/api/overview/generate'
}); };