// This file is auto-generated by @hey-api/openapi-ts

export type CheckReport = {
    timestamp: Instant;
    results: Array<CheckResult>;
    tier: Tier;
    tierCompletion?: number;
    tierAdvanceIn?: number;
};

export type CheckResult = {
    id: string;
    risk: Risk;
    title: string;
    summary: string;
    description: string;
    mitigation: string;
};

export type Instant = string;

export type Risk = 'DISABLED' | 'UNKNOWN' | 'LOW' | 'MODERATE' | 'HIGH';

export type Tier = 'GOLD' | 'SILVER' | 'BRONZE';

export type PostApiCheckByIdDisableData = {
    path: {
        id: string;
    };
};

export type PostApiCheckByIdDisableResponse = (unknown);

export type PostApiCheckByIdDisableError = unknown;

export type PostApiCheckByIdEnableData = {
    path: {
        id: string;
    };
};

export type PostApiCheckByIdEnableResponse = (number);

export type PostApiCheckByIdEnableError = unknown;

export type GetApiReportResponse = (CheckReport);

export type GetApiReportError = unknown;

export type PostApiReportGenerateResponse = (unknown);

export type PostApiReportGenerateError = unknown;