// This file is auto-generated by @hey-api/openapi-ts

export type Attributes = {
    friendly_name?: (string) | null;
};

export type CheckResult = {
    id: string;
    risk: Risk;
    title: string;
    summary: string;
    description: string;
    mitigation: string;
};

export type Instant = string;

export type Report = {
    id?: (number) | null;
    timestamp: Instant;
    results: Array<CheckResult>;
    tier: Tier;
    tierCompletion?: number;
    tierAdvanceIn?: number;
};

export type Risk = 'DISABLED' | 'UNKNOWN' | 'LOW' | 'MODERATE' | 'HIGH';

export type State = {
    entity_id: string;
    state: string;
    attributes: Attributes;
    last_changed: Instant;
    last_reported: Instant;
    last_updated: Instant;
    context: {
        [key: string]: (string);
    };
};

export type Tier = 'GOLD' | 'SILVER' | 'BRONZE';

export type GetApiDevicesResponse = (Array<State>);

export type GetApiDevicesError = unknown;

export type GetApiLogsResponse = ({
    [key: string]: Array<(string)>;
});

export type GetApiLogsError = unknown;

export type GetApiLogsUnifiedResponse = (Array<(string)>);

export type GetApiLogsUnifiedError = unknown;

export type GetApiOverviewResponse = (Report);

export type GetApiOverviewError = unknown;

export type PostApiOverviewCheckByIdDisableData = {
    path: {
        id: string;
    };
};

export type PostApiOverviewCheckByIdDisableResponse = (unknown);

export type PostApiOverviewCheckByIdDisableError = unknown;

export type PostApiOverviewCheckByIdEnableData = {
    path: {
        id: string;
    };
};

export type PostApiOverviewCheckByIdEnableResponse = (number);

export type PostApiOverviewCheckByIdEnableError = unknown;

export type PostApiOverviewGenerateResponse = (unknown);

export type PostApiOverviewGenerateError = unknown;