// This file is auto-generated by @hey-api/openapi-ts

export type CheckReport = {
    timestamp: Instant;
    results: Array<CheckResult>;
};

export type CheckResult = {
    risk: Risk;
    title: string;
    summary: string;
    description: string;
    mitigation: string;
};

export type Instant = string;

export type Risk = 'UNKNOWN' | 'LOW' | 'MODERATE' | 'HIGH';

export type PostApiCheckResponse = (unknown);

export type PostApiCheckError = unknown;

export type GetApiReportResponse = (CheckReport);

export type GetApiReportError = unknown;