name: "Cybersecurity Dashboard"
version: "dev"
slug: "cybersecurity_dashboard"
description: "Improve your cybersecurity of your smart home"
panel_icon: "mdi:security"
arch:
  - amd64
init: false
ingress: true
ingress_port: 8080
hassio_role: manager
hassio_api: true
homeassistant_api: true
options:
  log_level: "INFO"
  instance_url: ""
  github_api_token: ""
schema:
  log_level: "str"
  instance_url: "str"
  github_api_token: "str"
