name: "Security Dashboard"
slug: "security_dashboard"
version: "1.0.0"
description: "Improve your cybersecurity awareness"
init: false
ingress: true
ingress_port: 8080
image: "ghcr.io/trthingnes/ha-security-addon-{arch}"
arch:
  - amd64
  - aarch64