name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - addon/**

jobs:
  publish-amd64:
    name: Build and publish (amd64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository from GitHub
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with Home Assistant builder
        uses: home-assistant/builder@master
        with:
          args: |
            --target addon \
            --amd64
  publish-aarch64:
    name: Build and publish (aarch64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository from GitHub
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with Home Assistant builder
        uses: home-assistant/builder@master
        with:
          args: |
            --target addon \
            --aarch64