name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [amd64, aarch64]
    steps:
      - name: Checkout the repository from GitHub
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push with Home Assistant builder
        uses: home-assistant/builder@master
        with:
          args: |
            --target . \
            --docker-hub ghcr.io \
            --image ${{ github.repository }}-{arch} \
            --${{ matrix.arch }}