name: Update add-on repository
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Copy config.yaml
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
            source-files: 'config.yaml'
            destination-username: 'trthingnes'
            destination-repository: 'hassio-addons'
            destination-branch: 'main'
            destination-directory: 'security-dashboard'
            commit-username: 'GitHub Action'
            commit-email: 'support@github.com'
            commit-message: 'Update config.yaml'