name: "Test"

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository from GitHub
        uses: actions/checkout@v3
      - name: Build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --target addon \
            --amd64